In [ ]:
import tensorflow_hub as hub
import tensorflow_hub as hub
import tensorflow_text as text
import tensorflow as tf

In [ ]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed

{'input_type_ids': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 'input_mask': <tf.Tensor: shape

In [ ]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results

{'pooled_output': <tf.Tensor: shape=(2, 768), dtype=float32, numpy=
 array([[-0.79177403, -0.21411912,  0.49769545, ...,  0.24465235,
         -0.47334474,  0.81758696],
        [-0.91712314, -0.47935176, -0.7865697 , ..., -0.6175175 ,
         -0.71026856,  0.921843  ]], dtype=float32)>,
 'sequence_output': <tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.07292047,  0.08567817,  0.14476831, ..., -0.09677088,
           0.08722127,  0.07711085],
         [ 0.1783942 , -0.19006078,  0.5034952 , ..., -0.05869824,
           0.32717073, -0.15578493],
         [ 0.18701449, -0.43388748, -0.4887515 , ..., -0.15502778,
           0.00145182, -0.24471016],
         ...,
         [ 0.12083091,  0.12884252,  0.46453542, ...,  0.0737552 ,
           0.17441946,  0.16522075],
         [ 0.07967882, -0.01190652,  0.502254  , ...,  0.13777725,
           0.21002197,  0.00624588],
         [-0.07212701, -0.28303462,  0.59033376, ...,  0.475519  ,
           0.16668482, -0.08920349

In [ ]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [ ]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177403, -0.21411912,  0.49769545, ...,  0.24465235,
        -0.47334474,  0.81758696],
       [-0.91712314, -0.47935176, -0.7865697 , ..., -0.6175175 ,
        -0.71026856,  0.921843  ]], dtype=float32)>

In [ ]:
from transformers import BertTokenizer , TFBertModel

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
text = "nice movie indeed "
text2  = "I love python programming"

tokens = tokenizer(
    text,
    text2,
    padding='max_length',
    max_length=512,
    return_tensors='tf',

)




In [ ]:
tokens

{'input_ids': <tf.Tensor: shape=(1, 512), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,  1045,  2293, 18750,  4730,
          102,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0, 

In [ ]:

encoder = TFBertModel.from_pretrained("bert-base-uncased")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
output= encoder(tokens , output_hidden_states=True)

In [ ]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 512, 768), dtype=float32, numpy=
array([[[-0.046156  ,  0.02669894, -0.04622757, ..., -0.32109755,
          0.21157117,  0.47390693],
        [ 0.20424496, -0.2279785 ,  0.5327624 , ..., -0.09399597,
          0.29066283, -0.10692753],
        [ 0.22694533,  0.0013016 , -0.26526242, ..., -0.06171334,
          0.08479568, -0.31772467],
        ...,
        [-0.0565873 ,  0.03222833,  0.39271307, ...,  0.08721349,
          0.03693664,  0.05405266],
        [-0.11969294, -0.25347304,  0.22472827, ...,  0.4001663 ,
          0.0769304 , -0.11383151],
        [-0.07261239, -0.19617733,  0.64291656, ...,  0.47134715,
          0.12611815, -0.08298727]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.90783954, -0.5625742 , -0.76627   ,  0.7739627 ,  0.51729804,
        -0.24428105,  0.9065315 ,  0.38267988, -0.6009129 , -0.9999927 ,
        -0.3220307 ,  0.82

In [ ]:
# Accès :
output.keys()

odict_keys(['last_hidden_state', 'pooler_output', 'hidden_states'])

In [ ]:
from transformers import BertTokenizer, TFBertModel

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = TFBertModel.from_pretrained("bert-base-uncased", output_hidden_states=True)

inputs = tokenizer("nice movie indeed", "I love python programming", return_tensors='tf', padding='max_length', max_length=512, truncation=True)
outputs = model(**inputs)


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 512), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,  1045,  2293, 18750,  4730,
          102,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0, 

In [ ]:
outputs

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 512, 768), dtype=float32, numpy=
array([[[-0.046156  ,  0.02669894, -0.04622757, ..., -0.32109755,
          0.21157117,  0.47390693],
        [ 0.20424496, -0.2279785 ,  0.5327624 , ..., -0.09399597,
          0.29066283, -0.10692753],
        [ 0.22694533,  0.0013016 , -0.26526242, ..., -0.06171334,
          0.08479568, -0.31772467],
        ...,
        [-0.0565873 ,  0.03222833,  0.39271307, ...,  0.08721349,
          0.03693664,  0.05405266],
        [-0.11969294, -0.25347304,  0.22472827, ...,  0.4001663 ,
          0.0769304 , -0.11383151],
        [-0.07261239, -0.19617733,  0.64291656, ...,  0.47134715,
          0.12611815, -0.08298727]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.90783954, -0.5625742 , -0.76627   ,  0.7739627 ,  0.51729804,
        -0.24428105,  0.9065315 ,  0.38267988, -0.6009129 , -0.9999927 ,
        -0.3220307 ,  0.82

In [ ]:
print(output.keys())


odict_keys(['last_hidden_state', 'pooler_output', 'hidden_states'])
